### ISSUE TITLE
Slides Link a github.com

### ISSUE THREAD

**Issue by rodpoblete** [iv-devs/curso-python#1]
El link de [slides](#) **redireciona al home de github**. Eso es porque aún no está subida la presentación? 😶

**Comment by cristofer-dev** [comment]
hay que pedirle a @erick el link y hacer update

**Comment by cristofer-dev** [comment]
@rodpoblete consigue las Slides..

**Comment by rodpoblete** [comment]
**erick** esta trabajando con ellas, me dijo que en la semana las subía. Le falta agregar unos ejercicios de **Jupyter Notebook** (*La semana termina el Domingo..*😬)
